<!DOCTYPE html>
<html lang="en"><head>
<script src="sum_to_zero_files/libs/clipboard/clipboard.min.js"></script>
<script src="sum_to_zero_files/libs/quarto-html/tabby.min.js"></script>
<script src="sum_to_zero_files/libs/quarto-html/popper.min.js"></script>
<script src="sum_to_zero_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="sum_to_zero_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="sum_to_zero_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="sum_to_zero_files/libs/quarto-html/quarto-syntax-highlighting-e97fc0c53e03b0d912b748b5c8c98638.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="sum_to_zero_files/libs/quarto-contrib/alpine-3.12/buttons.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Sean Pinkney">
  <meta name="author" content="Nikolai Vetr">
  <title>Population Effect Estimation in Bayesian Hierarchical Models Using Sum-to-Zero Constraints</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="sum_to_zero_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="sum_to_zero_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #d8dee9; background-color: #2e3440; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #d8dee9; } /* Normal */
    code span.al { color: #bf616a; background-color: #3b4252; font-weight: bold; } /* Alert */
    code span.an { color: #d08770; } /* Annotation */
    code span.at { color: #8fbcbb; } /* Attribute */
    code span.bn { color: #b48ead; } /* BaseN */
    code span.bu { color: #88c0d0; font-style: italic; } /* BuiltIn */
    code span.cf { color: #81a1c1; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #ebcb8b; } /* Char */
    code span.cn { color: #eceff4; font-weight: bold; } /* Constant */
    code span.co { color: #616e88; } /* Comment */
    code span.cv { color: #e5e9f0; } /* CommentVar */
    code span.do { color: #5e81ac; } /* Documentation */
    code span.dt { color: #81a1c1; } /* DataType */
    code span.dv { color: #b48ead; } /* DecVal */
    code span.er { color: #bf616a; text-decoration: underline; } /* Error */
    code span.ex { color: #8fbcbb; font-weight: bold; } /* Extension */
    code span.fl { color: #b48ead; } /* Float */
    code span.fu { color: #88c0d0; } /* Function */
    code span.im { color: #a3be8c; } /* Import */
    code span.in { color: #ebcb8b; } /* Information */
    code span.kw { color: #81a1c1; font-weight: bold; } /* Keyword */
    code span.op { color: #81a1c1; } /* Operator */
    code span.ot { color: #8fbcbb; } /* Other */
    code span.pp { color: #5e81ac; } /* Preprocessor */
    code span.re { color: #88c0d0; background-color: #3b4252; } /* RegionMarker */
    code span.sc { color: #ebcb8b; } /* SpecialChar */
    code span.ss { color: #d08770; } /* SpecialString */
    code span.st { color: #a3be8c; } /* String */
    code span.va { color: #5e81ac; } /* Variable */
    code span.vs { color: #a3be8c; } /* VerbatimString */
    code span.wa { color: #bf616a; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="sum_to_zero_files/libs/revealjs/dist/theme/quarto-48620ee4811eece0313b2ba3d6b03046.css">
  <link rel="stylesheet" href="styles.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="sum_to_zero_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="sum_to_zero_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="sum_to_zero_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="sum_to_zero_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Population Effect Estimation in Bayesian Hierarchical Models Using<br>Sum-to-Zero Constraints</h1>
  <p class="subtitle">StanCon 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Sean Pinkney 
</div>
<div class="quarto-title-author-email">
<a href="mailto:sean.pinkney@gmail.com">sean.pinkney@gmail.com</a>
</div>
        <p class="quarto-title-affiliation">
            SVP Measurement Analytics at Publicis Groupe
          </p>
        <p class="quarto-title-affiliation">
            Stan Developer
          </p>
    </div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Nikolai Vetr 
</div>
<div class="quarto-title-author-email">
<a href="mailto:nikgvetr@stanford.edu">nikgvetr@stanford.edu</a>
</div>
        <p class="quarto-title-affiliation">
            Department of Pathology, Stanford University
          </p>
    </div>
</div>

</section>
<section id="slides-and-code-at" class="slide level2">
<h2>Slides and code at</h2>

<img data-src="images/repo_qr.png" class="quarto-figure quarto-figure-center r-stretch" width="380"><p style="text-align: center;">
<a href="https://github.com/spinkney/open-talks">github.com/spinkney/open-talks</a>
</p>
</section>
<section id="agenda" class="slide level2">
<h2>Agenda</h2>
<ul>
<li>What is a sum-to-zero constraint?</li>
<li>Hierarchical models between frequentist and bayesian approaches</li>
<li>How is it possible to translate between them?</li>
<li>Implications</li>
</ul>
</section>
<section id="what-is-a-sum-to-zero-constraint" class="slide level2">
<h2>What is a sum-to-zero constraint?</h2>
<p>It’s simply <span class="math display">
\sum_j^n a_j = 0
</span> To construct one might randomly draw i.i.d. <span class="math inline">n - 1</span> values <span class="math inline">y</span> and</p>
<div style="font-size: 80%;">
<p><span class="math display">
\begin{aligned}
y_n &amp; \overset{\text{set}}= -\sum_i^{n - 1} y_i \\
\boldsymbol{z} &amp;= \left[ y_1 \; y_2 \; \ldots \; y_{n- 1} \; y_n\right]  \\
&amp; \sum_i^n z = 0
\end{aligned}
</span></p>
</div>
<p>This works and is a valid construction. The problem is that it induces strong prior assumptions about the relationships across <span class="math inline">\boldsymbol{z}</span>.</p>
</section>
<section id="what-is-a-sum-to-zero-constraint-1" class="slide level2">
<h2>What is a sum-to-zero constraint?</h2>
<p>Since only <span class="math inline">z_n</span> is a function of <span class="math inline">y</span> the marginal density will be the density of the sum of <span class="math inline">z_{i:n - 1}</span>. Most modelers would not want this!</p>

<img data-src="sum_to_zero_files/figure-revealjs/density-overlay-1.svg" class="quarto-figure quarto-figure-center r-stretch" style="width:90.0%"><div style="font-size: 80%;">
<p>The implicit prior on the last element is clearly different. Furthermore, the covariance of the final element is coupled strongly with the other elements.</p>
</div>
</section>
<section id="what-is-a-sum-to-zero-constraint-2" class="slide level2">
<h2>What is a sum-to-zero constraint?</h2>
<p>We can balance the density across the values by using an orthonormal basis for the zero-sum subspace, <span class="math inline">QQ^\top=P_0=I_n-\frac1n\mathbf 1_n\mathbf 1_n^\top</span>.</p>

<img data-src="sum_to_zero_files/figure-revealjs/zero-sum-basis-map-1.svg" class="quarto-figure quarto-figure-center r-stretch" style="width:95.0%"><p>All the values are now isotropic and exchangeable.</p>
</section>
<section id="bayesian-hierarchical-models" class="slide level2">
<h2>Bayesian hierarchical models</h2>
<div class="columns">
<div class="column" style="width: 50%;">
<p><img data-src="sum_to_zero_files/figure-revealjs/bayesian-hierarchy-1.svg" width="960"></p>
</div><div class="column" style="width: 50%; font-size: 75%;">
<p>Sharing of information happens</p>
<ul>
<li><span class="math inline">\Phi</span> population distribution</li>
<li>Globally</li>
<li>Bi-directionally</li>
<li>Partial pooling</li>
</ul>
<p>When the evidence or data for a parameter are</p>
<ul>
<li>low
<ul>
<li>estimate is closer to prior</li>
</ul></li>
<li>large
<ul>
<li>data swamps prior</li>
<li>prior pull is weak</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="frequentist-hierarchical-models" class="slide level2">
<h2>Frequentist hierarchical models</h2>
<div class="columns">
<div class="column" style="width: 50%;">
<p><img data-src="sum_to_zero_files/figure-revealjs/frequentist-hierarchy-1.svg" width="960"></p>
</div><div class="column" style="width: 50%; font-size: 75%;">
<p>No population distribution <span class="math inline">\Phi</span></p>
<ul>
<li>the <span class="math inline">\theta_j</span> are <strong>fixed unknowns</strong>, not draws</li>
<li>no pooling: each <span class="math inline">\theta_j</span> is estimated from group <span class="math inline">j</span> data alone</li>
<li>information flows one way, <span class="math inline">\theta_j \rightarrow y_j</span></li>
</ul>
<p>Groups are tied together only by a <em>hard</em> constraint</p>
<ul>
<li>e.g.&nbsp;effects coding <span class="math inline">\textstyle\sum_j \theta_j = 0</span></li>
<li>identifies the grand mean instead of a population parameter</li>
</ul>
</div></div>
</section>
<section id="what-is-the-population-effect" class="slide level2">
<h2>What is the population effect?</h2>
<p>Let’s take a 2-level, varying slopes, varying intercept model with <span class="math inline">i</span> units and <span class="math inline">j</span> groups</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="sum_to_zero_files/figure-revealjs/varying-effects-equation-1.svg" class="quarto-figure quarto-figure-center" style="width:44.0%"></p>
</figure>
</div>
<div style="font-size: 80%;">
<p><strong>Group-level (conditional):</strong> <span class="math inline">E(y_{ij} \mid X, j) = \alpha + a_j + X (\beta + b_j)</span></p>
<p><strong>Population-level (marginal):</strong> <span class="math inline">E(y_{ij} \mid X) = \alpha + X \beta</span><br>
when <span class="math inline">E(a_j) = E(b_j) = 0</span></p>
</div>

<aside class="notes">
<p>The marginal estimand only exists in the random-effects world — there’s no distribution over groups to marginalize against otherwise. The E(a_j) = 0 condition is an identification convention, not a substantive assumption: any nonzero mean would just be absorbed into alpha.</p>
<p>In the fixed-effects world the analogue is the average over the observed groups, alpha + a-bar + X(beta + b-bar), and the hard constraint sum a_j = 0 is what makes alpha the grand mean.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside><div>
<p>Assuming linear link functions. Under a nonlinear link <span class="math inline">E(y \mid X) \neq g^{-1}(\alpha + X\beta)</span>.</p>
</div></aside></section>
<section id="different-populations" class="slide level2">
<h2>Different populations</h2>
<p>The data inform the group coefficients <span class="math inline">\alpha_j</span> and <span class="math inline">\beta_j</span> whereas the population <span class="math inline">\alpha</span> and <span class="math inline">\beta</span> sit one level up.</p>
<div class="columns">
<div class="column" style="width: 50%; font-size: 75%; border-right: 1px solid #d0d0d0; padding-right: 1.5em; box-sizing: border-box;">
<p><span class="emphasis2">Bayesian hierarchical model</span></p>
<p><span class="math inline">\alpha</span> and <span class="math inline">\beta</span> are <em>population</em> parameters and the observed groups are <strong>draws from</strong> that population</p>
<p><span class="math display">
a_j \sim \mathcal{N}(\alpha, \sigma_a), \quad b_j \sim \mathcal{N}(\beta, \sigma_b)
</span></p>
<p>A benefit is that new groups may still be infered from the population distribution as any finite draw of <span class="math inline">J</span> groups has</p>
<p><span class="math display">
\bar{a} = \tfrac{1}{J}\textstyle\sum_j a_j \neq \alpha
</span></p>
</div><div class="column" style="width: 50%; font-size: 75%; padding-left: 1.5em; box-sizing: border-box;">
<p><span class="emphasis">Frequentist effects coding</span></p>
<p>No population to draw from — the <span class="math inline">J</span> observed groups <strong>are</strong> the population</p>
<p>The “population” parameter is the finite-population grand mean</p>
<p><span class="math display">
\alpha = \tfrac{1}{J}\textstyle\sum_j \left( \alpha + a_j \right) \iff \sum_j a_j = 0
</span></p>
</div></div>
</section>
<section id="is-there-an-equivalence" class="slide level2">
<h2>Is there an equivalence?</h2>
<p>Suppose we restrict to varying intercepts, <span class="math inline">x_i \sim \mathcal{N}(\alpha + a_j, \sigma_x)</span>:</p>
<div class="columns">
<div class="column" style="width: 50%; font-size: 75%; border-right: 1px solid #d0d0d0; padding-right: 1.5em; box-sizing: border-box;">
<p><span class="emphasis2">Bayesian hierarchical model</span></p>
<p><span class="math display">
a^{\text{bayes}}_j \sim \mathcal{N}(0, \sigma_a)
</span> <span class="math display">
\bar{a} =\frac{1}{J} \sum_j a^{\text{bayes}}_j \sim \mathcal{N}\left(0, \frac{\sigma_a^2}{J} \right)
</span></p>
</div><div class="column" style="width: 50%; font-size: 75%; padding-left: 1.5em; box-sizing: border-box;">
<p><span class="emphasis">Frequentist effects coding</span></p>
<p><span class="math display">
\alpha = \tfrac{1}{J}\textstyle\sum_j \left( \alpha + a^{\text{s2z}}_j \right) \iff \sum_j a^{\text{s2z}}_j = 0
</span></p>
</div></div>
<div style="font-size: 75%;">
<p>Take <span class="math display">
\begin{aligned}
\alpha_{\text{s2z}} &amp;\overset{\text{set}} = \alpha_{\text{bayes}} + \bar{a} \\
a_j^{\text{s2z}}  &amp;\overset{\text{set}} = a_j^{\text{bayes}} - \bar{a} \\
\sum a_j^{\text{s2z}} &amp;= 0
\end{aligned}
</span></p>
</div>
</section>
<section id="does-it-work" class="slide level2">
<h2>Does it work?</h2>
<p>Let’s simulate six deliberately unbalanced groups from <span class="math display">
x_i \sim \mathcal{N}(\alpha + a_{j[i]}, \sigma_x), \qquad
a_j \sim \mathcal{N}(0, \tau^2),
</span> with</p>
<pre><code>alpha = 5
tau = 2.5
sigma_x = 1
n_j = (8, 13, 21, 34, 55, 89)</code></pre>
<p>For this finite draw,</p>
<p><span class="math display">
\frac{1}{J} \sum_j a^{\text{bayes}}_j = \bar a = 0.85, \qquad
\alpha_{\mathrm{s2z}} = 5.85.
</span></p>
<div style="font-size: 78%;">
<p>Sampling 10k iterations over 4 chains. The first Stan program samples unconstrained Bayesian varying effects; the second samples a <code>sum_to_zero_vector</code> directly.</p>
</div>
</section>
<section id="conversion" class="slide level2 conversion-code-slide">
<h2>Conversion</h2>
<p>Bayesian specification and conversion to sum-to-zero equivalent</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan"><span id="cb2-1"><a href=""></a><span class="kw">data</span> {</span>
<span id="cb2-2"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>&gt; N;</span>
<span id="cb2-3"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">2</span>&gt; J;</span>
<span id="cb2-4"><a href=""></a>  <span class="dt">array</span>[N] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>, <span class="kw">upper</span>=J&gt; group;</span>
<span id="cb2-5"><a href=""></a>  <span class="dt">vector</span>[N] x;</span>
<span id="cb2-6"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; alpha_prior_sd;</span>
<span id="cb2-7"><a href=""></a>}</span>
<span id="cb2-8"><a href=""></a><span class="kw">parameters</span> {</span>
<span id="cb2-9"><a href=""></a>  <span class="dt">real</span> alpha_bayes;</span>
<span id="cb2-10"><a href=""></a>  <span class="dt">vector</span>[J] a_bayes;</span>
<span id="cb2-11"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; tau;</span>
<span id="cb2-12"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; sigma_x;</span>
<span id="cb2-13"><a href=""></a>}</span>
<span id="cb2-14"><a href=""></a><span class="kw">model</span> {</span>
<span id="cb2-15"><a href=""></a>  alpha_bayes ~ normal(<span class="dv">0</span>, alpha_prior_sd);</span>
<span id="cb2-16"><a href=""></a>  a_bayes ~ normal(<span class="dv">0</span>, tau);</span>
<span id="cb2-17"><a href=""></a>  tau ~ normal(<span class="dv">0</span>, <span class="dv">5</span>);</span>
<span id="cb2-18"><a href=""></a>  sigma_x ~ normal(<span class="dv">0</span>, <span class="dv">2</span>);</span>
<span id="cb2-19"><a href=""></a>  x ~ normal(alpha_bayes + a_bayes[group], sigma_x);</span>
<span id="cb2-20"><a href=""></a>}</span>
<span id="cb2-21"><a href=""></a><span class="kw">generated quantities</span> {</span>
<span id="cb2-22"><a href=""></a>  <span class="dt">real</span> mean_a = mean(a_bayes);</span>
<span id="cb2-23"><a href=""></a>  <span class="dt">real</span> alpha_s2z_recovered = alpha_bayes + mean_a;</span>
<span id="cb2-24"><a href=""></a>  <span class="dt">vector</span>[J] a_s2z_recovered = a_bayes - mean_a;</span>
<span id="cb2-25"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="the-two-fits-agree" class="slide level2">
<h2>The two fits agree</h2>

<img data-src="sum_to_zero_files/figure-revealjs/compare-varying-intercept-fits-1.svg" class="quarto-figure quarto-figure-center r-stretch" style="width:92.0%"><div style="font-size: 67%;">
<p>Across <span class="math inline">\alpha_{\mathrm{s2z}}</span> and the six <span class="math inline">a_j^{\mathrm{s2z}}</span>, the largest posterior-mean difference is 0.002. Across every plotted parameter, the largest difference is 0.003: Monte Carlo error at the scale of the plot.</p>
</div>
</section>
<section id="prior-work-and-the-missing-connection" class="slide level2 nostretch literature-positioning-slide">
<h2>Prior work and the missing connection</h2>
<div class="columns">
<div class="column" style="width: 59%; font-size: 57%; line-height: 1.12; border-right: 1px solid #d0d0d0; padding-right: 1.4em; box-sizing: border-box;">
<p><span class="emphasis2">Established pieces</span></p>
<ul>
<li><span class="citation" data-cites="gelman2005">Gelman (<a href="#/references" role="doc-biblioref" onclick="">2005</a>)</span> distinguishes finite-population and superpopulation quantities.</li>
<li><span class="citation" data-cites="rouder2012">Rouder et al. (<a href="#/references" role="doc-biblioref" onclick="">2012</a>)</span> compare constrained fixed effects with exchangeable random effects.</li>
<li><span class="citation" data-cites="vines1996">Vines, Gilks, and Wild (<a href="#/references" role="doc-biblioref" onclick="">1996</a>)</span> introduce sweeping: replace <span class="math inline">a_j</span> by <span class="math inline">a_j-\bar a</span> and absorb <span class="math inline">\bar a</span> into the intercept.</li>
<li><span class="citation" data-cites="millar2009">Millar, Fryer, and Hirst (<a href="#/references" role="doc-biblioref" onclick="">2009</a>)</span> show that sweeping changes inference from the population mean to the sample mean—and leave recovery as future work.</li>
<li><span class="citation" data-cites="ogle2020">Ogle and Barber (<a href="#/references" role="doc-biblioref" onclick="">2020</a>)</span> extend sweeping to nested and crossed effect sets, but in the forward direction rather than from an S2Z fit back to the superpopulation posterior.</li>
</ul>
</div><div class="column" style="width: 41%; font-size: 60%; line-height: 1.14; padding-left: 1.4em; box-sizing: border-box;">
<p><span class="emphasis">Missing connection</span></p>
<p>Prior derivations address a single batch of group effects, normal–normal hierarchical models, or hierarchical centering and sweeping. We have not found an explicit posterior equivalence between an <strong>induced-prior sum-to-zero parameterization</strong> and a <strong>Bayesian superpopulation model</strong>.</p>
<p><span class="emphasis2">This work</span></p>
<p>Establishes that equivalence through <strong>stochastic reconstruction of the omitted common-shift directions</strong>, extending to</p>
<ul>
<li>heterogeneous scales,</li>
<li>elliptically symmetric priors, and</li>
<li>multiple batches of varying effects.</li>
</ul>
</div></div>
</section>
<section id="what-about-going-from-sum-to-zero-to-population-models" class="slide level2 nostretch population-derivation-slide">
<h2>What about going from sum-to-zero to population models?</h2>
<div style="font-size: 66%; line-height: 1.12;">
<p>Given <span class="math inline">\tau</span>, let <span class="math inline">v_{\bar{a}}=\tau^2/J</span> and under the prior assumption that <span class="math inline">\alpha_{\mathrm{bayes}}\perp\bar a\mid\tau</span>. Then</p>
<p><span class="math display">
\begin{gathered}
\alpha_{\mathrm{bayes}}\sim\mathcal N(0,s_\alpha^2),
\qquad \bar a\mid\tau\sim\mathcal N(0, v_{\bar{a}}),\\[0.35em]
\alpha_{\mathrm{s2z}}=\alpha_{\mathrm{bayes}}+\bar a
\ \Longrightarrow\
\begin{cases}
\operatorname{Var}(\alpha_{\mathrm{s2z}}\mid\tau)=s_\alpha^2 + v_{\bar{a}}, \\
\operatorname{Cov}(\bar a,\alpha_{\mathrm{s2z}}\mid\tau) = v_{\bar{a}},
\end{cases}\\[0.45em]
\begin{pmatrix}\bar a \\ \alpha_{\mathrm{s2z}}\end{pmatrix}\Bigm|\tau
\sim\mathcal N\!\left[
\begin{pmatrix}0\\0\end{pmatrix},
\begin{pmatrix}v_{\bar{a}} &amp; v_{\bar{a}} \\ v_{\bar{a}} &amp;s_\alpha^2 + v_{\bar{a}} \end{pmatrix}
\right].
\end{gathered}
</span></p>
<p>The conditional-normal formula therefore gives</p>
<p><span class="math display">
\begin{gathered}
\bar a\mid\alpha_{\mathrm{s2z}},\tau
\sim\mathcal N\!\left(w\alpha_{\mathrm{s2z}},v_c\right),\\[0.35em]
\underbrace{\frac{v_{\bar{a}}}{s_\alpha^2 + v_{\bar{a}}}}_{w},
\qquad
\underbrace{v_{\bar{a}} - \frac{v_{\bar{a}}^2}{s_\alpha^2 + v_{\bar{a}}}}_{v_c}.
\end{gathered}
</span></p>
</div>
</section>
<section id="what-about-going-from-sum-to-zero-to-population-models-1" class="slide level2 s2z-conversion-code-slide nostretch">
<h2>What about going from sum-to-zero to population models?</h2>
<div style="font-size: 64%; line-height: 1.08;">
<p>For each sum-to-zero posterior draw, sample the missing realized mean and shift the coordinates:</p>
<p><span class="math display">
\bar{a} \mid \alpha_{\mathrm{s2z}}, \tau
\sim \mathcal N(w\alpha_{\mathrm{s2z}},v_c), \qquad
\alpha_{\mathrm{bayes}} = \alpha_{\mathrm{s2z}} - \bar{a}, \qquad
a_j^{\mathrm{bayes}} = a_j^{\mathrm{s2z}} + \bar{a},
</span></p>
<p>where <span class="math inline">\mathcal N(\text{mean},\text{variance})</span> is used.</p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan"><span id="cb3-1"><a href=""></a><span class="kw">parameters</span> {</span>
<span id="cb3-2"><a href=""></a>  <span class="dt">real</span> alpha_s2z; <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; tau, sigma_x;</span>
<span id="cb3-3"><a href=""></a>  sum_to_zero_vector[J] a_s2z;</span>
<span id="cb3-4"><a href=""></a>}</span>
<span id="cb3-5"><a href=""></a><span class="kw">model</span> {</span>
<span id="cb3-6"><a href=""></a>  tau ~ normal(<span class="dv">0</span>, <span class="dv">5</span>); sigma_x ~ normal(<span class="dv">0</span>, <span class="dv">2</span>);</span>
<span id="cb3-7"><a href=""></a>  alpha_s2z ~ normal(<span class="dv">0</span>, hypot(alpha_prior_sd, tau / sqrt(J)));</span>
<span id="cb3-8"><a href=""></a>  a_s2z ~ normal(<span class="dv">0</span>, tau);</span>
<span id="cb3-9"><a href=""></a>  <span class="kw">target +=</span> log(tau);</span>
<span id="cb3-10"><a href=""></a>  x ~ normal(alpha_s2z + a_s2z[group], sigma_x);</span>
<span id="cb3-11"><a href=""></a>}</span>
<span id="cb3-12"><a href=""></a><span class="kw">generated quantities</span> {</span>
<span id="cb3-13"><a href=""></a>  <span class="dt">real</span> mean_a_bayes, alpha_bayes_recovered;</span>
<span id="cb3-14"><a href=""></a>  <span class="dt">vector</span>[J] a_bayes_recovered;</span>
<span id="cb3-15"><a href=""></a>  {</span>
<span id="cb3-16"><a href=""></a>    <span class="dt">real</span> var_mean_a = square(tau) / J;</span>
<span id="cb3-17"><a href=""></a>    <span class="dt">real</span> var_alpha = square(alpha_prior_sd);</span>
<span id="cb3-18"><a href=""></a>    <span class="dt">real</span> weight = var_mean_a / (var_alpha + var_mean_a);</span>
<span id="cb3-19"><a href=""></a>    <span class="dt">real</span> conditional_sd = sqrt(var_alpha * var_mean_a / (var_alpha + var_mean_a));</span>
<span id="cb3-20"><a href=""></a>    mean_a_bayes = normal_rng(weight * alpha_s2z, conditional_sd);</span>
<span id="cb3-21"><a href=""></a>  }</span>
<span id="cb3-22"><a href=""></a>  alpha_bayes_recovered = alpha_s2z - mean_a_bayes;</span>
<span id="cb3-23"><a href=""></a>  a_bayes_recovered = a_s2z + mean_a_bayes;</span>
<span id="cb3-24"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Centering J independent normal effects induces covariance <span class="math inline">\tau^2 (I - \mathbf{1}\mathbf{1}^\top / J)</span> on the zero-sum subspace. The direct model therefore uses the same subspace scale tau.</p>
<p>The <code>target += log(tau)</code> term restores the missing scale factor because the constrained vector has J - 1 degrees of freedom while the vectorized normal density supplies J normalizing terms.</p>
<p>Conditional on tau, mean(a_bayes) has standard deviation tau / sqrt(J). Convolving it with the alpha_bayes prior gives the induced alpha_s2z prior in the direct program.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="back-to-bayesian-the-two-fits-agree" class="slide level2">
<h2>Back to Bayesian: the two fits agree</h2>

<img data-src="sum_to_zero_files/figure-revealjs/compare-reconstructed-bayes-fits-1.svg" class="quarto-figure quarto-figure-center r-stretch" style="width:92.0%"><div style="font-size: 70%;">
<p>Across <span class="math inline">\alpha_{\text{bayes}}</span> and the six <span class="math inline">a_j^{\text{bayes}}</span>, the largest posterior-mean difference is 0.032. Across every plotted parameter, the largest difference is 0.032. The largest standardized gap is 1.6 combined Monte Carlo SEs.</p>
</div>
</section>
<section id="ess-and-essgrad-on-the-two-parameterizations" class="slide level2">
<h2>ESS and ESS/grad on the two parameterizations</h2>
<table class="ess-table">
<thead>
<tr>
<th rowspan="2">
Parameter
</th>
<th class="ess-group ess-group-bayes" colspan="2">
Bayesian
</th>
<th class="ess-group ess-group-s2z" colspan="2">
Sum-to-zero
</th>
</tr>
<tr>
<th class="ess-subhead ess-subhead-bayes">
ESS
</th>
<th class="ess-subhead ess-subhead-bayes">
ESS/grad
</th>
<th class="ess-subhead ess-subhead-s2z">
ESS
</th>
<th class="ess-subhead ess-subhead-s2z">
ESS/grad
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
α
</td>
<td>
5,557
</td>
<td>
0.002
</td>
<td>
33,461
</td>
<td>
0.121
</td>
</tr>
<tr>
<td>
<i>a</i><sub>1</sub>
</td>
<td>
5,719
</td>
<td>
0.002
</td>
<td>
39,725
</td>
<td>
0.144
</td>
</tr>
<tr>
<td>
<i>a</i><sub>2</sub>
</td>
<td>
5,683
</td>
<td>
0.002
</td>
<td>
64,383
</td>
<td>
0.234
</td>
</tr>
<tr>
<td>
<i>a</i><sub>3</sub>
</td>
<td>
5,650
</td>
<td>
0.002
</td>
<td>
71,686
</td>
<td>
0.260
</td>
</tr>
<tr>
<td>
<i>a</i><sub>4</sub>
</td>
<td>
5,588
</td>
<td>
0.002
</td>
<td>
56,372
</td>
<td>
0.204
</td>
</tr>
<tr>
<td>
<i>a</i><sub>5</sub>
</td>
<td>
5,581
</td>
<td>
0.002
</td>
<td>
46,215
</td>
<td>
0.168
</td>
</tr>
<tr>
<td>
<i>a</i><sub>6</sub>
</td>
<td>
5,572
</td>
<td>
0.002
</td>
<td>
39,120
</td>
<td>
0.142
</td>
</tr>
<tr>
<td>
τ
</td>
<td>
11,574
</td>
<td>
0.004
</td>
<td>
57,662
</td>
<td>
0.209
</td>
</tr>
<tr>
<td>
σ<sub><i>x</i></sub>
</td>
<td>
16,549
</td>
<td>
0.006
</td>
<td>
61,344
</td>
<td>
0.223
</td>
</tr>
</tbody>
</table>
<div class="ess-note">
<p>4 chains × 10,000 sampling iterations = 40,000 post-warmup draws, plus 4,000 warmup iterations per chain. Bulk ESS is pooled across chains. ESS/grad divides by the total post-warmup <code>n_leapfrog__</code>: Bayesian = 2,796,128; sum-to-zero = 275,672.</p>
</div>
</section>
<section id="idea-on-one-slide" class="slide level2 implications-slide">
<h2>Idea on one slide</h2>
<div class="implications-pairs">
<div class="implications-pair implications-copy">
<p>Super-population decomposition</p>
</div>
<div class="implications-pair implications-math">
<p><span class="math display">
  \begin{aligned}
  \underbrace{\alpha_{\mathrm{s2z}}}_{\text{mean of varying }J\text{ groups}}
    &amp;=\underbrace{\alpha_{\mathrm{bayes}}}_{\text{super-population mean}} + \underbrace{\frac{1}{J}\sum a^{\text{bayes}}_j}_{\bar{a}},\\
  \bar{a} \mid\tau&amp;\sim\mathcal N(0,\tau^2/J)
  \end{aligned}
  </span></p>
</div>
<div class="implications-pair implications-copy">
<p>For every draw from the induced-prior sum-to-zero fit, draw the missing common shift from the prior-implied conditional distribution. This restores the Bayesian super-population draw.</p>
</div>
<div class="implications-pair implications-math">
<p><span class="math display">
  \begin{aligned}
  \bar{a} \mid\alpha_{\mathrm{s2z}},\tau
    &amp;\sim\mathcal N(w\alpha_{\mathrm{s2z}},v_c),\\
  \alpha_{\mathrm{Bayes}}^{\mathrm{rec}}
    &amp;=\alpha_{\mathrm{s2z}} - \bar{a},\\
  \mathbf a_{\mathrm{Bayes}}^{\mathrm{rec}}
    &amp;=\mathbf a_{\mathrm{s2z}}+ \bar{a} \mathbf 1.
  \end{aligned}
  </span></p>
</div>
<div class="implications-pair implications-copy">
<p>The native Bayesian and sum-to-zero estimates are different. Equivalence is distributional and holds only after randomly augmenting the sum-to-zero draws.</p>
</div>
<div class="implications-pair implications-math">
<p><span class="math display">
  (\alpha_{\mathrm{Bayes}}^{\mathrm{rec}},
   \mathbf a_{\mathrm{Bayes}}^{\mathrm{rec}})\mid y
  \ \overset{d}{=}\
  (\alpha_{\mathrm{Bayes}},\mathbf a_{\mathrm{Bayes}})\mid y,
  </span></p>
</div>
<div class="implications-pair implications-copy">
<p>Extends to varying prior standard deviations on the varying effects. Common in Bayesian models and we can derive similar logic.</p>
</div>
<div class="implications-pair implications-math">
<ul>
<li>Repeat the decomposition on the log-SD scale: <span class="math display">
\log s_j=\gamma_{\mathrm{s2z}}+b_j^{\mathrm{s2z}},
\qquad \mathbf 1^\top\mathbf b_{\mathrm{s2z}}=0,
</span> then restore <span class="math inline">\bar b</span>.</li>
</ul>
</div>
</div>
</section>
<section id="from-one-common-sd-to-group-specific-sds" class="slide level2 nostretch">
<h2>From one common SD to group-specific SDs</h2>
<div style="font-size: 68%;">
<p>The original model used one common prior SD <span class="math inline">\tau</span> for every varying intercept. We now learn a separate prior SD <span class="math inline">s_j</span> for each group:</p>
<p><span class="math display">
a_j\mid\tau\sim\mathcal N(0,\tau^2)
\qquad\Longrightarrow\qquad
a_j\mid s_j\sim\mathcal N(0,s_j^2),\quad j=1,\ldots,J.
</span></p>
<p>The <span class="math inline">J</span> positive scales are partially pooled through a log-scale hierarchy:</p>
<p><span class="math display">
\gamma\sim\mathcal N(\mu_\gamma,s_\gamma^2),
\qquad
b_j\mid\omega\sim\mathcal N(0,\omega^2),
\qquad
s_j=\exp(\gamma+b_j).
</span></p>
<p>Here <span class="math inline">\exp(\gamma)</span> is their shared geometric center and <span class="math inline">\omega</span> is the new hyper-SD controlling how much the group log scales vary.</p>
<p>Apply the earlier sum-to-zero shift to the log-SD deviations:</p>
<p><span class="math display">
\begin{gathered}
\bar b=J^{-1}\sum_j b_j,\qquad
b_j^{\mathrm{s2z}}=b_j-\bar b,\qquad
\gamma_{\mathrm{s2z}}=\gamma+\bar b,\\
\log s_j=\gamma+b_j
=\gamma_{\mathrm{s2z}}+b_j^{\mathrm{s2z}}.
\end{gathered}
</span></p>
</div>
</section>
<section id="different-variances-on-the-varying-intercepts" class="slide level2 nostretch">
<h2>Different variances on the varying intercepts</h2>
<div style="font-size: 71%;">
<p>The statistical model uses the nonnegative hyper-SD <span class="math inline">\omega</span>:</p>
<p><span class="math display">
\gamma\sim\mathcal N(\mu_\gamma,s_\gamma^2),
\qquad
b_j\mid\omega\sim\mathcal N(0,\omega^2),
\qquad
\log s_j=\gamma+b_j.
</span></p>
<p><span class="math inline">\omega</span> is the sampled magnitude, coded as the signed form <span class="math inline">\lambda_\omega</span> to preserve continuity at zero.</p>
<p><span class="math display">
\begin{gathered}
\lambda_\omega\sim\mathcal N(0,0.25^2),\qquad
\omega=|\lambda_\omega|,\\
z_j\sim\mathcal N(0,1),\qquad
b_j=\lambda_\omega z_j.
\end{gathered}
</span></p>
<p>Because <span class="math inline">z_j</span> is symmetric, <span class="math inline">\lambda_\omega=+\omega</span> and <span class="math inline">\lambda_\omega=-\omega</span> induce the same <span class="math inline">b_j\mid\omega\sim\mathcal N(0,\omega^2)</span>.</p>
<p><span class="math display">
\sum_j z_j^{\mathrm{s2z}}=0,
\qquad
b_j^{\mathrm{s2z}}=\lambda_\omega z_j^{\mathrm{s2z}},
\qquad
\gamma_{\mathrm{s2z}}=\gamma+\bar b.
</span></p>
<p>The removed mean has variance <span class="math inline">\lambda_\omega^2/J=\omega^2/J</span>, so</p>
<p><span class="math display">
\boxed{
\operatorname{Var}(\gamma_{\mathrm{s2z}}\mid\lambda_\omega)
=s_\gamma^2+\frac{\lambda_\omega^2}{J}
=s_\gamma^2+\frac{\omega^2}{J}
}.
</span></p>
</div>
</section>
<section id="recovery" class="slide level2 nostretch recovery-slide">
<h2>Recovery</h2>
<div style="font-size: 60%; line-height: 1.08;">
<p><strong>Recovering the removed log-scale mean <span class="math inline">\bar b</span></strong></p>
<p>Let <span class="math inline">v_b = \lambda_\omega^2/J=\omega^2/J</span> and <span class="math inline">V = s_\gamma^2+v_b</span>. Then</p>
<p><span class="math display">
\bar b\mid\gamma_{\mathrm{s2z}},\lambda_\omega
\sim\mathcal N\!\left(
\frac{v_b}{V}(\gamma_{\mathrm{s2z}}-\mu_\gamma),
\frac{s_\gamma^2v_b}{V}
\right),
</span></p>
<p>where the second argument is a variance. Using <span class="math inline">z_{\bar b}\sim\mathcal N(0,1)</span>, recover</p>
<p><span class="math display">
\begin{aligned}
\bar b
&amp;=\frac{v_b}{V}(\gamma_{\mathrm{s2z}}-\mu_\gamma)
+\lambda_\omega
\sqrt{\frac{s_\gamma^2}{JV}}\,z_{\bar b},\\
\gamma&amp;=\gamma_{\mathrm{s2z}}-\bar b,
\qquad
b_j=b_j^{\mathrm{s2z}}+\bar b.
\end{aligned}
</span></p>
<p><strong>Recovering the removed varying-effect mean <span class="math inline">m</span></strong></p>
<p>Let <span class="math inline">m=\bar a_{\mathrm{bayes}}=J^{-1}\sum_j a_j^{\mathrm{bayes}}</span> be the mean removed from the unconstrained Bayesian effects. Given <span class="math inline">s_\alpha</span>, <span class="math inline">s_j</span>, <span class="math inline">\alpha_{\mathrm{s2z}}</span>, and <span class="math inline">a^{\mathrm{s2z}}</span>, define</p>
<p><span class="math display">
P=s_\alpha^{-2}+\sum_j s_j^{-2},
\qquad
\widehat m=P^{-1}\!\left(
\frac{\alpha_{\mathrm{s2z}}}{s_\alpha^2}
-\sum_j\frac{a_j^{\mathrm{s2z}}}{s_j^2}
\right).
</span></p>
<p>Then <span class="math inline">m\mid\alpha_{\mathrm{s2z}},a^{\mathrm{s2z}},s_\alpha,\{s_j\}
\sim\mathcal N(\widehat m,P^{-1})</span> and <span class="math inline">\alpha_{\mathrm{bayes}}=\alpha_{\mathrm{s2z}}-m</span>, <span class="math inline">a_j^{\mathrm{bayes}}=a_j^{\mathrm{s2z}}+m</span>.</p>
</div>
</section>
<section id="different-variances-the-two-fits-agree" class="slide level2">
<h2>Different variances: the two fits agree</h2>

<img data-src="sum_to_zero_files/figure-revealjs/compare-heterogeneous-varying-intercept-fits-1.svg" class="quarto-figure quarto-figure-center r-stretch" style="width:92.0%"><div style="font-size: 70%;">
<p>The shared log scale has a <span class="math inline">\mathcal N(\log 2.5,0.5^2)</span> prior, and <span class="math inline">\lambda_\omega \sim\operatorname{Normal}(0,0.25)</span>. Conditional on them, <span class="math inline">s_j=\exp(\gamma+b_j)</span> with <span class="math inline">b_j\sim\mathcal N(0,\omega^2)</span>.</p>
</div>
</section>
<section id="conventional-versus-s2z-efficiency" class="slide level2">
<h2>Conventional versus S2Z efficiency</h2>
<table class="ess-table efficiency-summary-table">
<thead>
<tr>
<th>
Metric
</th>
<th class="ess-group ess-group-bayes">
Conventional
</th>
<th class="ess-group ess-group-s2z">
S2Z coordinates
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Post-warmup leapfrog steps
</td>
<td>
4,051,292
</td>
<td>
284,280
</td>
</tr>
<tr>
<td>
Wall-clock fit time
</td>
<td>
4.3 s
</td>
<td>
0.7 s
</td>
</tr>
<tr>
<td>
Bulk ESS for α
</td>
<td>
8,108
</td>
<td>
58,604
</td>
</tr>
<tr>
<td>
Bulk ESS/grad for α
</td>
<td>
0.00200
</td>
<td>
0.20615
</td>
</tr>
</tbody>
</table>
<div class="ess-note">
<p>Both fits had zero divergences and zero maximum-treedepth hits. Wall-clock time is CmdStanR’s total elapsed fit time for four parallel chains, including warmup and sampling but excluding compilation; it is machine-specific.</p>
</div>
</section>
<section id="sampling-efficiency-effects-and-sds" class="slide level2">
<h2>Sampling efficiency: effects and SDs</h2>
<table class="ess-table hetero-ess-table">
<colgroup>
<col class="hetero-parameter-col">
<col span="4" class="hetero-metric-col">
</colgroup>
<thead>
<tr>
<th rowspan="2">
Parameter
</th>
<th class="ess-group ess-group-bayes" colspan="2">
Conventional
</th>
<th class="ess-group ess-group-s2z" colspan="2">
S2Z coordinates
</th>
</tr>
<tr>
<th class="ess-subhead ess-subhead-bayes">
ESS
</th>
<th class="ess-subhead ess-subhead-bayes">
ESS/grad
</th>
<th class="ess-subhead ess-subhead-s2z">
ESS
</th>
<th class="ess-subhead ess-subhead-s2z">
ESS/grad
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
α
</td>
<td>
8,108
</td>
<td>
0.00200
</td>
<td>
58,604
</td>
<td>
0.20615
</td>
</tr>
<tr>
<td>
<i>a</i><sub><i>j</i></sub> (mean)
</td>
<td>
8,264
</td>
<td>
0.00204
</td>
<td>
58,463
</td>
<td>
0.20565
</td>
</tr>
<tr>
<td>
<i>ā</i>
</td>
<td>
8,110
</td>
<td>
0.00200
</td>
<td>
58,919
</td>
<td>
0.20726
</td>
</tr>
<tr>
<td>
σ<sub><i>x</i></sub>
</td>
<td>
39,248
</td>
<td>
0.00969
</td>
<td>
67,397
</td>
<td>
0.23708
</td>
</tr>
<tr class="parameter-block-start">
<td>
<i>s</i><sub>α</sub>
</td>
<td>
27,305
</td>
<td>
0.00674
</td>
<td>
60,411
</td>
<td>
0.21251
</td>
</tr>
<tr>
<td>
<i>s</i><sub><i>j</i></sub> (mean)
</td>
<td>
25,778
</td>
<td>
0.00636
</td>
<td>
37,942
</td>
<td>
0.13347
</td>
</tr>
<tr>
<td>
λ<sub>ω</sub>
</td>
<td>
27,275
</td>
<td>
0.00673
</td>
<td>
50,933
</td>
<td>
0.17916
</td>
</tr>
</tbody>
</table>
<div class="ess-note">
<p>The <span class="math inline">a_j</span> and <span class="math inline">s_j</span> rows report means across the six group-specific parameters; their individual ESS and ESS/grad values had similar magnitudes. Matched Bayesian estimands use 40,000 post-warmup draws. ESS/grad divides by total post-warmup <code>n_leapfrog__</code>: conventional = 4,051,292; S2Z coordinates = 284,280. <span class="math inline">s_\alpha</span> is the population-intercept prior SD, <span class="math inline">s_j</span> is the prior SD of varying intercept <span class="math inline">a_j</span>, and <span class="math inline">\omega</span> is the SD of the group log-SD deviations.</p>
</div>
</section>
<section id="ess-per-gradient-as-groups-grow" class="slide level2 nostretch">
<h2>ESS per gradient as groups grow</h2>
<div class="cell" data-layout-align="center" data-fig-bg="transparent">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="sum_to_zero_files/figure-revealjs/plot-heterogeneous-scaling-benchmark-1.svg" class="quarto-figure quarto-figure-center" style="width:96.0%"></p>
</figure>
</div>
</div>
</div>
<div class="ess-note">
<p>This single nested benchmark extends the original <span class="math inline">\tau=2.5</span> simulation by repeating its six unbalanced group sizes through <span class="math inline">J=(10,20,50,100)</span>, yielding <span class="math inline">N=(296;\,681;\,1{,}781;\,3{,}596)</span>. Points show median ESS/grad across the matched group-specific estimands; bars show their IQR, not uncertainty intervals.</p>
</div>
</section>
<section id="take-away" class="slide level2">
<h2>Take-away</h2>
<p>Bayesian hierarchical models allow estimating a ‘super-population’ but it’s not magic, it is a consequence of the distributional assumptions.</p>
<p>Sum-to-zero constraints are great and now you can get the Bayesian estimates with faster and more robust fitting.</p>
<p>Arguments here extend to elliptically symmetric distributions.</p>
<p>More details to come in the paper</p>
<ul>
<li>Multiple sets of varying effects</li>
<li>Argument extension to - elliptically symmetric distributions - varying slopes</li>
</ul>
</section>
<section id="thank-you" class="slide level2">
<h2>Thank you!</h2>

<img data-src="images/repo_qr.png" class="quarto-figure quarto-figure-center r-stretch" width="380"><p style="text-align: center;">
<a href="https://github.com/spinkney/open-talks">github.com/spinkney/open-talks</a>
</p>
</section>
<section id="appendix" class="slide level2">
<h2>Appendix</h2>
<p>Comparison diagnostics, Stan implementations, and Gaussian marginalization details</p>
</section>
<section id="on-the-difference-between-two-posterior-means" class="slide level2 nostretch">
<h2>On the difference between two posterior means</h2>
<div style="font-size: 72%;">
<p>For each plotted parameter, calculate <span class="math display">
z=
\frac{|\hat\mu_1-\hat\mu_2|}
{\sqrt{\operatorname{MCSE}_1^2+
       \operatorname{MCSE}_2^2}}.
</span></p>
</div>
<table class="comparison-gap-table">
<thead>
<tr>
<th>
Fit comparison
</th>
<th>
Largest absolute posterior-mean difference
</th>
<th>
Largest standardized gap, <i>z</i>
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Recovered S2Z vs native S2Z
</td>
<td>
0.003
</td>
<td>
1.8
</td>
</tr>
<tr>
<td>
Native Bayesian vs recovered Bayesian
</td>
<td>
0.032
</td>
<td>
1.6
</td>
</tr>
<tr>
<td>
Different variances: conventional vs recovered Bayesian
</td>
<td>
0.008
</td>
<td>
0.5
</td>
</tr>
</tbody>
</table>
<div class="comparison-gap-note">
<p>Each entry is the maximum across the plotted parameters for that comparison; the two maxima need not occur for the same parameter. The largest standardized gap was 1.8 combined Monte Carlo SEs. For one standard-normal comparison, a gap at least this large occurs about 7% of the time; taking a maximum over several parameters makes it still less surprising.</p>
</div>
</section>
<section id="differing-variances-conventional-bayesian-stan-model-declarations" class="slide level2 long-code-title">
<h2>Differing variances conventional Bayesian Stan model: declarations</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4" data-startfrom="1"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan"><span id="cb4-1"><a href=""></a><span class="kw">data</span> {</span>
<span id="cb4-2"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>&gt; N;</span>
<span id="cb4-3"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">2</span>&gt; J;</span>
<span id="cb4-4"><a href=""></a>  <span class="dt">array</span>[N] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>, <span class="kw">upper</span>=J&gt; group;</span>
<span id="cb4-5"><a href=""></a>  <span class="dt">vector</span>[N] x;</span>
<span id="cb4-6"><a href=""></a>}</span>
<span id="cb4-7"><a href=""></a><span class="kw">transformed data</span> {</span>
<span id="cb4-8"><a href=""></a>  <span class="dt">real</span> mu_gamma = log(<span class="fl">2.5</span>);</span>
<span id="cb4-9"><a href=""></a>  <span class="dt">real</span> s_gamma = <span class="fl">0.5</span>;</span>
<span id="cb4-10"><a href=""></a>}</span>
<span id="cb4-11"><a href=""></a><span class="kw">parameters</span> {</span>
<span id="cb4-12"><a href=""></a>  <span class="dt">real</span> alpha_bayes;</span>
<span id="cb4-13"><a href=""></a>  <span class="dt">vector</span>[J] a_bayes;</span>
<span id="cb4-14"><a href=""></a>  <span class="dt">real</span> gamma;</span>
<span id="cb4-15"><a href=""></a>  <span class="dt">vector</span>[J] z_log_sd;</span>
<span id="cb4-16"><a href=""></a>  <span class="dt">real</span> lambda_omega;</span>
<span id="cb4-17"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; sigma_x;</span>
<span id="cb4-18"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="differing-variances-conventional-bayesian-stan-model-sd-hierarchy-and-model" class="slide level2 long-code-title dense-code-slide">
<h2>Differing variances conventional Bayesian Stan model: SD hierarchy and model</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-startfrom="18"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan" style="counter-reset: source-line 17;"><span id="cb5-18"><a href=""></a>}</span>
<span id="cb5-19"><a href=""></a><span class="kw">transformed parameters</span> {</span>
<span id="cb5-20"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; alpha_prior_sd = exp(gamma);</span>
<span id="cb5-21"><a href=""></a>  <span class="dt">vector</span>[J] b = lambda_omega * z_log_sd;</span>
<span id="cb5-22"><a href=""></a>  <span class="dt">vector</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt;[J] a_prior_sd = exp(gamma + b);</span>
<span id="cb5-23"><a href=""></a>}</span>
<span id="cb5-24"><a href=""></a><span class="kw">model</span> {</span>
<span id="cb5-25"><a href=""></a>  gamma ~ normal(mu_gamma, s_gamma);</span>
<span id="cb5-26"><a href=""></a>  z_log_sd ~ std_normal();</span>
<span id="cb5-27"><a href=""></a>  lambda_omega ~ normal(<span class="dv">0</span>, <span class="fl">0.25</span>);</span>
<span id="cb5-28"><a href=""></a>  alpha_bayes ~ normal(<span class="dv">0</span>, alpha_prior_sd);</span>
<span id="cb5-29"><a href=""></a>  a_bayes ~ normal(<span class="dv">0</span>, a_prior_sd);</span>
<span id="cb5-30"><a href=""></a>  sigma_x ~ normal(<span class="dv">0</span>, <span class="dv">2</span>);</span>
<span id="cb5-31"><a href=""></a>  x ~ normal(alpha_bayes + a_bayes[group], sigma_x);</span>
<span id="cb5-32"><a href=""></a>}</span>
<span id="cb5-33"><a href=""></a><span class="kw">generated quantities</span> {</span>
<span id="cb5-34"><a href=""></a>  <span class="dt">real</span> mean_a = mean(a_bayes);</span>
<span id="cb5-35"><a href=""></a>  <span class="dt">real</span> alpha_s2z_recovered = alpha_bayes + mean_a;</span>
<span id="cb5-36"><a href=""></a>  <span class="dt">vector</span>[J] a_s2z_recovered = a_bayes - mean_a;</span>
<span id="cb5-37"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="s2z-stan-declarations" class="slide level2">
<h2>S2Z Stan: declarations</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-startfrom="1"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan"><span id="cb6-1"><a href=""></a><span class="kw">data</span> {</span>
<span id="cb6-2"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>&gt; N;</span>
<span id="cb6-3"><a href=""></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">2</span>&gt; J;</span>
<span id="cb6-4"><a href=""></a>  <span class="dt">array</span>[N] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>, <span class="kw">upper</span>=J&gt; group;</span>
<span id="cb6-5"><a href=""></a>  <span class="dt">vector</span>[N] x;</span>
<span id="cb6-6"><a href=""></a>}</span>
<span id="cb6-7"><a href=""></a><span class="kw">transformed data</span> {</span>
<span id="cb6-8"><a href=""></a>  <span class="dt">real</span> mu_gamma = log(<span class="fl">2.5</span>);</span>
<span id="cb6-9"><a href=""></a>  <span class="dt">real</span> s_gamma = <span class="fl">0.5</span>;</span>
<span id="cb6-10"><a href=""></a>}</span>
<span id="cb6-11"><a href=""></a><span class="kw">parameters</span> {</span>
<span id="cb6-12"><a href=""></a>  <span class="dt">real</span> alpha_s2z;</span>
<span id="cb6-13"><a href=""></a>  sum_to_zero_vector[J] a_s2z;</span>
<span id="cb6-14"><a href=""></a>  <span class="dt">real</span> z_mean_a_cond;</span>
<span id="cb6-15"><a href=""></a>  <span class="dt">real</span> gamma_s2z;</span>
<span id="cb6-16"><a href=""></a>  sum_to_zero_vector[J] z_log_sd_s2z;</span>
<span id="cb6-17"><a href=""></a>  <span class="dt">real</span> z_mean_b_cond;</span>
<span id="cb6-18"><a href=""></a>  <span class="dt">real</span> lambda_omega;</span>
<span id="cb6-19"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; sigma_x;</span>
<span id="cb6-20"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="s2z-stan-log-scale-constraint" class="slide level2">
<h2>S2Z Stan: log-scale constraint</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-startfrom="21"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan" style="counter-reset: source-line 20;"><span id="cb7-21"><a href=""></a><span class="kw">transformed parameters</span> {</span>
<span id="cb7-22"><a href=""></a>  <span class="dt">real</span> var_gamma = square(s_gamma);</span>
<span id="cb7-23"><a href=""></a>  <span class="dt">real</span> var_mean_b = square(lambda_omega) / J;</span>
<span id="cb7-24"><a href=""></a>  <span class="dt">real</span> var_gamma_s2z = var_gamma + var_mean_b;</span>
<span id="cb7-25"><a href=""></a>  <span class="dt">real</span> mean_b_cond = var_mean_b / var_gamma_s2z</span>
<span id="cb7-26"><a href=""></a>    * (gamma_s2z - mu_gamma);</span>
<span id="cb7-27"><a href=""></a>  <span class="dt">real</span> mean_b = mean_b_cond + lambda_omega</span>
<span id="cb7-28"><a href=""></a>      * sqrt(var_gamma / (J * var_gamma_s2z))</span>
<span id="cb7-29"><a href=""></a>      * z_mean_b_cond;</span>
<span id="cb7-30"><a href=""></a>  <span class="dt">real</span> gamma_recovered = gamma_s2z - mean_b;</span>
<span id="cb7-31"><a href=""></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; alpha_prior_sd_recovered =</span>
<span id="cb7-32"><a href=""></a>    exp(gamma_recovered);</span>
<span id="cb7-33"><a href=""></a>  <span class="dt">vector</span>[J] b_s2z = lambda_omega * z_log_sd_s2z;</span>
<span id="cb7-34"><a href=""></a>  <span class="dt">vector</span>[J] b_recovered = b_s2z + mean_b;</span>
<span id="cb7-35"><a href=""></a>  <span class="dt">vector</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt;[J] a_prior_sd =</span>
<span id="cb7-36"><a href=""></a>    exp(gamma_s2z + b_s2z);</span>
<span id="cb7-37"><a href=""></a>  <span class="dt">vector</span>[J] inv_var_a = inv(square(a_prior_sd));</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="s2z-stan-remove-the-effect-mean" class="slide level2">
<h2>S2Z Stan: remove the effect mean</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-startfrom="38"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan" style="counter-reset: source-line 37;"><span id="cb8-38"><a href=""></a>  <span class="dt">real</span> inv_var_alpha =</span>
<span id="cb8-39"><a href=""></a>    inv(square(alpha_prior_sd_recovered));</span>
<span id="cb8-40"><a href=""></a>  <span class="dt">real</span> precision_mean_a = inv_var_alpha + sum(inv_var_a);</span>
<span id="cb8-41"><a href=""></a>  <span class="dt">real</span> mean_a_cond = (alpha_s2z * inv_var_alpha</span>
<span id="cb8-42"><a href=""></a>      - dot_product(a_s2z, inv_var_a)) / precision_mean_a;</span>
<span id="cb8-43"><a href=""></a>  <span class="dt">real</span> sd_mean_a_cond = inv_sqrt(precision_mean_a);</span>
<span id="cb8-44"><a href=""></a>  <span class="dt">real</span> mean_a_bayes = mean_a_cond + sd_mean_a_cond * z_mean_a_cond;</span>
<span id="cb8-45"><a href=""></a>  <span class="dt">real</span> alpha_bayes_recovered = alpha_s2z - mean_a_bayes;</span>
<span id="cb8-46"><a href=""></a>  <span class="dt">vector</span>[J] a_bayes_recovered = a_s2z + mean_a_bayes;</span>
<span id="cb8-47"><a href=""></a>}</span>
<span id="cb8-48"><a href=""></a><span class="kw">model</span> {</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="s2z-stan-prior-and-likelihood" class="slide level2">
<h2>S2Z Stan: prior and likelihood</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-startfrom="48"><pre class="sourceCode numberSource stan number-lines code-with-copy"><code class="sourceCode stan" style="counter-reset: source-line 47;"><span id="cb9-48"><a href=""></a><span class="kw">model</span> {</span>
<span id="cb9-49"><a href=""></a>  gamma_s2z ~ normal(mu_gamma, sqrt(var_gamma_s2z));</span>
<span id="cb9-50"><a href=""></a>  z_log_sd_s2z ~ std_normal();</span>
<span id="cb9-51"><a href=""></a>  z_mean_b_cond ~ std_normal();</span>
<span id="cb9-52"><a href=""></a>  lambda_omega ~ normal(<span class="dv">0</span>, <span class="fl">0.25</span>);</span>
<span id="cb9-53"><a href=""></a></span>
<span id="cb9-54"><a href=""></a>  alpha_s2z - mean_a_cond ~ normal(<span class="dv">0</span>, alpha_prior_sd_recovered);</span>
<span id="cb9-55"><a href=""></a>  a_s2z + mean_a_cond ~ normal(<span class="dv">0</span>, a_prior_sd);</span>
<span id="cb9-56"><a href=""></a>  <span class="kw">target +=</span> <span class="fl">0.5</span> * log(<span class="dv">2</span> * pi()) - <span class="fl">0.5</span> * log(precision_mean_a);</span>
<span id="cb9-57"><a href=""></a>  z_mean_a_cond ~ std_normal();</span>
<span id="cb9-58"><a href=""></a>  sigma_x ~ normal(<span class="dv">0</span>, <span class="dv">2</span>);</span>
<span id="cb9-59"><a href=""></a>  x ~ normal(alpha_s2z + a_s2z[group], sigma_x);</span>
<span id="cb9-60"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="completing-the-square-in-the-removed-mean-m" class="slide level2 nostretch">
<h2>Completing the square in the removed mean <span class="math inline">m</span></h2>
<div style="font-size: 74%;">
<p>For fixed <span class="math inline">s_\alpha</span>, <span class="math inline">\{s_j\}</span>, <span class="math inline">\alpha_{\mathrm{s2z}}</span>, and <span class="math inline">a^{\mathrm{s2z}}</span>, write</p>
<p><span class="math display">
\ell(m)=
\log\mathcal N(\alpha_{\mathrm{s2z}}-m\mid0,s_\alpha^2)
+\sum_{j=1}^J
\log\mathcal N(a_j^{\mathrm{s2z}}+m\mid0,s_j^2).
</span></p>
<p>With <span class="math inline">P</span> and <span class="math inline">\widehat m</span> from the main presentation, completing the square gives</p>
<p><span class="math display">
\ell(m)=\ell(\widehat m)-\frac{P}{2}(m-\widehat m)^2.
</span></p>
<p>This immediately gives <span class="math inline">m\mid\alpha_{\mathrm{s2z}},a^{\mathrm{s2z}},s_\alpha,\{s_j\}
\sim\mathcal N(\widehat m,P^{-1})</span>.</p>
</div>
</section>
<section id="marginalizing-the-removed-mean-m" class="slide level2 nostretch">
<h2>Marginalizing the removed mean <span class="math inline">m</span></h2>
<div style="font-size: 74%;">
<p>From the completed square, <span class="math inline">\ell(m)=\ell(\widehat m)-\tfrac12P(m-\widehat m)^2</span>. Therefore, marginalizing the removed direction contributes</p>
<p><span class="math display">
\begin{aligned}
\log\!\int_{-\infty}^{\infty}e^{\ell(m)}\,dm
&amp;=\ell(\widehat m)+
\log\!\int_{-\infty}^{\infty}
e^{-\frac{P}{2}(m-\widehat m)^2}\,dm \\
&amp;=\ell(\widehat m)
+\frac12\log(2\pi)-\frac12\log P.
\end{aligned}
</span></p>
<p><span class="math display">
\boxed{
\Delta\log p
=\frac12\log(2\pi)-\frac12\log P
}
</span></p>
<p>Thus <span class="math inline">P={\tt precision\_mean\_a}</span>. This is a Gaussian integration factor, not a Jacobian. The <span class="math inline">-\tfrac12\log P</span> term must remain because <span class="math inline">P</span> depends on the sampled scales; <span class="math inline">\tfrac12\log(2\pi)</span> is constant and may be dropped. If <span class="math inline">m</span> were sampled directly, this marginalization term would not be added.</p>
</div>
</section>
<section id="distributions" class="slide level2">
<h2>Distributions</h2>
<p>We will restrict ourselves to elliptically symmetric distributions for hierarchical models, i.e., <span class="math display">
\begin{align*}
&amp;f(x) = c \, g(x^\top \Sigma_x^{-1}x), \\
&amp;\int_{\mathbb{R}^d} f(x) \, dx = 1
\end{align*}
</span> where<sup>1</sup></p>
<ul>
<li>the generator <span class="math inline">g(\cdot): \mathbb{R}^+ \rightarrow \mathbb{R}^+</span></li>
<li>the normalizing constant <span class="math inline">c</span> ensures <span class="math inline">f(x)</span> integrates to 1</li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p><span class="citation" data-cites="delmas_2024">Delmas (<a href="#/references" role="doc-biblioref" onclick="">2024</a>)</span></p></li></ol></aside></section>
<section id="distributions-1" class="slide level2">
<h2>Distributions</h2>
<p><span class="math display">
\begin{align*}
&amp;f(x) = c \, g(x^\top \Sigma_x^{-1}x), \\
&amp;\int_{\mathbb{R}^d} f(x) \, dx = 1
\end{align*}
</span></p>
<p>The choice of <span class="math inline">g</span> controls the tail behavior, allowing both light- and heavy-tailed priors within the same family:</p>
<ul>
<li>Normal: <span class="math inline">g(t) \propto e^{-t/2}</span></li>
<li>Student-<span class="math inline">t_\nu</span> (Cauchy at <span class="math inline">\nu = 1</span>): <span class="math inline">g(t) \propto \left(1 + t/\nu\right)^{-(\nu + d)/2}</span></li>
<li>Logistic: <span class="math inline">g(t) \propto e^{-t} / \left(1 + e^{-t}\right)^2</span></li>
<li>Laplace: <span class="math inline">g(t) \propto e^{-\sqrt{t}}</span></li>
</ul>
</section>
<section id="references" class="slide level2 smaller nostretch scrollable">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-delmas_2024" class="csl-entry" role="listitem">
Delmas, Jean-Pierre. 2024. <span>“Background on Real and Complex Elliptically Symmetric Distributions.”</span> In <em>Elliptically Symmetric Distributions in Signal Processing and Machine Learning</em>, edited by Jean-Pierre Delmas, Mohammed Nabil El Korso, Stefano Fortunati, and Frédéric Pascal, 1–34. Cham: Springer Nature Switzerland. <a href="https://doi.org/10.1007/978-3-031-52116-4_1">https://doi.org/10.1007/978-3-031-52116-4_1</a>.
</div>
<div id="ref-gelman2005" class="csl-entry" role="listitem">
Gelman, Andrew. 2005. <span>“Analysis of Variance—Why It Is More Important Than Ever.”</span> <em>The Annals of Statistics</em> 33 (1): 1–53. <a href="https://doi.org/10.1214/009053604000001048">https://doi.org/10.1214/009053604000001048</a>.
</div>
<div id="ref-millar2009" class="csl-entry" role="listitem">
Millar, Colin P., Robert J. Fryer, and David Hirst. 2009. <span>“Hierarchical Modelling of Scottish Fisheries Observer Data: The Underlying Model.”</span> Collaborative Report No. 01/09. Aberdeen, UK: Fisheries Research Services. <a href="https://www.researchgate.net/publication/259693119_Hierarchical_modelling_of_Scottish_fisheries_observer_data_The_underlying_model">https://www.researchgate.net/publication/259693119_Hierarchical_modelling_of_Scottish_fisheries_observer_data_The_underlying_model</a>.
</div>
<div id="ref-ogle2020" class="csl-entry" role="listitem">
Ogle, Kiona, and Jarrett J. Barber. 2020. <span>“Ensuring Identifiability in Hierarchical Mixed Effects <span>Bayesian</span> Models.”</span> <em>Ecological Applications</em> 30 (7): e02159. <a href="https://doi.org/10.1002/eap.2159">https://doi.org/10.1002/eap.2159</a>.
</div>
<div id="ref-rouder2012" class="csl-entry" role="listitem">
Rouder, Jeffrey N., Richard D. Morey, Paul L. Speckman, and Jordan M. Province. 2012. <span>“Default <span>Bayes</span> Factors for <span>ANOVA</span> Designs.”</span> <em>Journal of Mathematical Psychology</em> 56 (5): 356–74. <a href="https://doi.org/10.1016/j.jmp.2012.08.001">https://doi.org/10.1016/j.jmp.2012.08.001</a>.
</div>
<div id="ref-vines1996" class="csl-entry" role="listitem">
Vines, S. K., W. R. Gilks, and P. Wild. 1996. <span>“Fitting <span>Bayesian</span> Multiple Random Effects Models.”</span> <em>Statistics and Computing</em> 6 (4): 337–46. <a href="https://doi.org/10.1007/BF00143554">https://doi.org/10.1007/BF00143554</a>.
</div>
</div>

</section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="sum_to_zero_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="sum_to_zero_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="sum_to_zero_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="sum_to_zero_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="sum_to_zero_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="sum_to_zero_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="sum_to_zero_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="sum_to_zero_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="sum_to_zero_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

<script src="sum_to_zero_files/libs/quarto-contrib/alpine-3.12/alpine@3.12.min.js"></script>
</body></html>